# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-18 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List_of_regedit_buy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_completion', models.IntegerField(blank=True, verbose_name='Год договора')),
                ('onec_code', models.CharField(blank=True, max_length=50, verbose_name='Код в 1С')),
                ('name_of_buyer', models.TextField(blank=True, verbose_name='Наименование покупателя')),
                ('theme_of_contract', models.TextField(blank=True, verbose_name='Предмет договора')),
                ('number', models.TextField(blank=True, verbose_name='Номер')),
                ('date_of_contract', models.TextField(blank=True, verbose_name='Дата Договора')),
                ('expiration', models.TextField(blank=True, verbose_name='Срок действия договора')),
                ('total', models.TextField(blank=True, verbose_name='Сумма договора')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарии')),
                ('technical', models.TextField(blank=True, verbose_name='ТехОписание')),
                ('tags', models.TextField(blank=True, verbose_name='Теги')),
                ('status', models.TextField(blank=True, verbose_name='Статус')),
                ('subcontractor', models.TextField(blank=True, verbose_name='Подрядчик')),
                ('check_number', models.TextField(blank=True, verbose_name='№ договора с подрядчиком')),
            ],
        ),
    ]
